name: "Blitz3D Build Action"
description: "Reusable GitHub Action for compiling Blitz3D projects"

inputs:
  source:
    description: "Main Blitz3D source file, including file extension"
    required: true
  output:
    description: "Output folder"
    required: false
    default: "dist"
  name:
    description: "Name of the built executable, excluding file extension"
    required: true
    default: "build"
  bump_version:
    description: "Whether to bump the version number (true/false)"
    required: false
    default: ""
  step:
    description: "Type of build step (build, release, etc.)"
    required: false
    default: "build"

runs:
  using: "composite"
  steps:
    - name: "Set up Blitz3D Build Environment"
      if: always()
      id: blitzcc-setup
      shell: pwsh
      run: |
        & "${{ github.action_path }}/scripts/setup.ps1" `
    - name: "Build Blitz3D Project"
      if: ${{ inputs.step == 'build' }}
      shell: pwsh
      run: |
        & "${{ github.action_path }}/scripts/build.ps1" `
          "${{ inputs.source }}" `
          "${{ inputs.output }}" `
          "${{ inputs.name }}" `
          "${{ inputs.bump_version }}" `
          "${{ steps.blitzcc-setup.outputs.compiler_path }}"